name: Create a complete package for Hyperlane Backed
on:
  push:

  workflow_dispatch:
   inputs:
     create_release:
       description: "Create a GitHub release"
       required: true
       type: boolean
     release_tag:
       description: "Release tag (example: v1.0.0)"
       required: true
       type: string

jobs:
  build:

    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04

    runs-on: ${{ matrix.os }}

    env:
      KDA_TOOL_VERSION: 1.2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Checkout Hyperlane Monorepo
        uses: actions/checkout@v6
        with:
          repository: kinesis-bridge/hyperlane-monorepo-kda-community
          path: hyperlane
          ref: kadena-support-develop

      - name: Checkout keys repos
        uses: actions/checkout@v6
        with:
          repository: kinesis-bridge/kadena-hyperlane-keys
          path: keys

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install Node JS
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install KDA tool
        run: |
          ARCHIVE=kda-tool-${KDA_TOOL_VERSION}-${{ matrix.os }}.tar.gz
          wget -nv https://github.com/kda-community/kda-tool/releases/download/${KDA_TOOL_VERSION}/$ARCHIVE
          tar xzf $ARCHIVE
          echo "KDA_TOOL_BIN=kda-tool-${KDA_TOOL_VERSION}/kda" >> "$GITHUB_ENV"

      - name: Build Hyperlane agents
        run: |
          cd hyperlane/rust
          cargo build --release --bin relayer
          cargo build --release --bin validator

      - name: Install Kadena proxy dependencies
        run: |
          cd hyperlane/typescript/agents/kadena-proxy
          yarn install

      - name: Prepare Webpack build
        run: |
          cd hyperlane/typescript/agents/kadena-proxy
          cat << EOF > webpack.config.js

          const path = require('path');
          module.exports = {
            entry: './src/main.ts',
            target: 'node',
            mode: 'production',
            externals: [],
            resolve: {
              extensions: ['.ts', '.js'],
            },
            output: {
              path: path.resolve(__dirname, 'dist'),
              filename: 'kadena_proxy.js',
            },
          };
          EOF

          tmp=$(mktemp) && \
          jq '.compilerOptions += {"webpack": true, "webpackConfigPath": "webpack.config.js"}' nest-cli.json > "$tmp"
          mv "$tmp" nest-cli.json

      - name: Build kadena proxy
        run: |
          cd hyperlane/typescript/agents/kadena-proxy
          yarn run nest build --webpack


      - name: Prepare configs
        run: |
          for f in *.yaml
            do yq -o=json '.' "$f" > "${f%.*}.json"
          done

      - name: Prepare Full artifact
        run: |
          DIST=dist
          AGENTS_DIR=$DIST/agents
          KEYS_DIR=$DIST/keys
          PROXY_DIR=$DIST/proxy
          CONFIG_DIR=$DIST/config
          TOOLS_DIR=$DIST/tools
          SYSTEMD_DIR=$DIST/systemd

          mkdir -p $AGENTS_DIR
          cp hyperlane/rust/target/release/relayer $AGENTS_DIR
          cp hyperlane/rust/target/release/validator $AGENTS_DIR

          strip $AGENTS_DIR/validator
          strip $AGENTS_DIR/relayer

          mkdir -p $PROXY_DIR
          cp hyperlane/typescript/agents/kadena-proxy/dist/kadena_proxy.js $PROXY_DIR

          mkdir -p $KEYS_DIR
          cp keys/ethereum_operators.json $KEYS_DIR
          cp keys/kadena_relayers.yaml.gpg $KEYS_DIR
          cp keys/kadena_validators.yaml.gpg $KEYS_DIR

          cat proxy_config_env > $PROXY_DIR/.env

          mkdir -p $CONFIG_DIR
          cp *.json $CONFIG_DIR

          mkdir $TOOLS_DIR
          cp ~/.foundry/bin/cast $TOOLS_DIR
          cp $KDA_TOOL_BIN $TOOLS_DIR

          mkdir $SYSTEMD_DIR
          cp systemd/* $SYSTEMD_DIR

      - name: Upload dist artifact
        uses: actions/upload-artifact@v7
        with:
          include-hidden-files: true
          name: build-${{ matrix.os }}-${{github.sha}}
          path: dist/

      - name: Prepare Systemd version
        env:
          MATRIX_OS: ${{ matrix.os }}
        run: |
          DIST=hyperlane_kadena_validator
          cp -rf dist $DIST

          ## Move the systemd scripts
          mv $DIST/systemd/start*.sh $DIST

          mkdir -p $DIST/systemd-units
          mv $DIST/systemd/*.service $DIST/systemd-units

          rm -rf $DIST/systemd

          tar czf hyperlane_kadena_systemd_${MATRIX_OS}_${GITHUB_SHA}.tar.gz -C $DIST .

      - name: Upload Systemd archive
        uses: actions/upload-artifact@v7
        with:
          path: hyperlane_kadena_systemd_${{ matrix.os }}_${{github.sha}}.tar.gz
          archive: false

  release:
    needs: build
    if: github.event_name == 'workflow_dispatch' && inputs.create_release == true

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Create artifacts dir
        run: |
          mkdir -p release_artifacts


      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: hyperlane_kadena_systemd_*
          merge-multiple: true
          path: release_artifacts/

      - name: Checkout Repository
        uses:  actions/checkout@v6

      - name: Prepare templates
        run: |
          for f in *_template.yaml
              do yq -o=json '.' "$f" > "release_artifacts/${f%.*}.json"
          done

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release_artifacts/*"
          body: "Kadena Systemd Package Release"
          tag: inputs.release_tag