name: Create a complete package for Hyperlane Backed
on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      KDA_TOOL_VERSION: 1.2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout Hyperlane Monorepo
        uses: actions/checkout@v4
        with:
          repository: kinesis-bridge/hyperlane-monorepo-kda-community
          path: hyperlane
          ref: kadena-support-develop

      - name: Checkout keys repos
        uses: actions/checkout@v4
        with:
          repository: kinesis-bridge/kadena-hyperlane-keys
          path: keys

      - name: Install JSON/YAML tools
        run: |
          sudo apt-get update
          sudo apt-get install -y yq jq

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install Node JS
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install KDA tool
        run: |
          ARCHIVE=kda-tool-${KDA_TOOL_VERSION}-${{ runner.name }}".tar.gz
          wget https://github.com/kda-community/kda-tool/releases/download/${KDA_TOOL_VERSION}/$ARCHIVE
          tar xzf $ARCHIVE
          echo "KDA_TOOL_BIN=kda-tool-${KDA_TOOL_VERSION}/kda" >> "$GITHUB_ENV"

      - name: Build Hyperlane agents
        run: |
          cd hyperlane/rust
          cargo build --release --bin relayer
          cargo build --release --bin validator

      - name: Install Kadena proxy dependencies
        run: |
          cd hyperlane/typescript/agents/kadena-proxy
          yarn install

      - name: Prepare Webpack build
        run: |
          cd hyperlane/typescript/agents/kadena-proxy
          cat << EOF > webpack.config.js

          const path = require('path');
          module.exports = {
            entry: './src/main.ts',
            target: 'node',
            mode: 'production',
            externals: [],
            resolve: {
              extensions: ['.ts', '.js'],
            },
            output: {
              path: path.resolve(__dirname, 'dist'),
              filename: 'kadena_proxy.js',
            },
          };
          EOF

          tmp=$(mktemp) && \
          jq '.compilerOptions += {"webpack": true, "webpackConfigPath": "webpack.config.js"}' nest-cli.json > "$tmp"
          mv "$tmp" nest-cli.json

      - name: Build kadena proxy
        run: |
          cd hyperlane/typescript/agents/kadena-proxy
          yarn run nest build --webpack


      - name: Prepare configs
        run: |
          for f in *.yaml
            do yq '.' "$f" > "${f%.*}.json"
          done

      - name: Prepare artifact
        run: |
          mkdir -p dist/agents
          cp hyperlane/rust/target/release/relayer dist/agents
          cp hyperlane/rust/target/release/validator dist/agents

          strip dist/agents/validator
          strip dist/agents/relayer

          mkdir -p dist/proxy
          cp hyperlane/typescript/agents/kadena-proxy/dist/kadena_proxy.js dist/proxy

          mkdir -p dist/encrypted_keys
          cp keys/ethereum_operators.json dist/encrypted_keys
          cp keys/kadena_relayers.yaml.gpg dist/encrypted_keys
          cp keys/kadena_validators.yaml.gpg dist/encrypted_keys

          cat proxy_config_env > dist/proxy/.env

          mkdir -p dist/config
          cp *.json dist/config

          mkdir dist/tools
          cp .foundry/bin/cast dist/tools
          cp $KDA_TOOL_BIN dist/tools



      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/